# we could add a 
# includeExcludeFilters:
#   include: [ string ] # List of items to include.
trigger:
  batch: true
  branches:
    include:
      - "main"

resources:
  repositories:
    - repository: templates
      type: git
      name: astro-template
      persistCredentials: true
    - repository: azure-dns
      type: git
      name: azure-dns
      persistCredentials: true

pool:
  vmImage: "windows-latest"

stages:
  - stage: Build_Astro
    jobs:
      - template: pipelines/build-astro.yml@templates

  - stage: Develop
    displayName: '1: Develop'
    dependsOn: DNS_Zone
    jobs:
      - template: pipelines/release-astro.yml@templates
        parameters:
          stack: "dev"
          environmentName: "dev"
          projectName: "william_portfolio"

  - stage: Production
    displayName: '2: Production'
    dependsOn: DNS_Zone
    jobs:
      - template: pipelines/release-astro.yml@templates
        parameters:
          stack: "prod"
          environmentName: "prd"
          projectName: "william_portfolio"

